'use strict';

// Centralized redaction paths — PHI/PII and sensitive fields
const REDACT_PATHS = [
  // Request headers/body (pino-http attaches req/res objects)
  'req.headers.authorization',
  'req.headers.cookie',
  'req.headers.set-cookie',
  'req.headers.x-api-key',
  'req.headers.x-csrf-token',
  'req.body.password',
  'req.body.currentPassword',
  'req.body.newPassword',
  'req.body.token',
  'req.body.resetToken',
  'req.body.gradingToken',
  'req.body.email',
  'req.body.newEmail',
  'req.body.notes',
  'req.body.note',
  'req.body.query',
  'req.body.prompt',
  'req.body.presentation',
  // Case intake and free-text fields
  'req.body.caseText',
  'req.body.symptoms',
  'req.body.labs',
  'req.body.medications',
  'req.body.comorbidities',
  'req.body.age',
  'req.body.sex',
  'req.body.message',
  'req.body.content',
  'req.body.freeText',
  'req.body.scenario',
  'req.body.input',
  // Root-level top keys
  'email',
  'token',
  'prompt',
  'query',
  'presentation',
  'notes',
  'note',
  'caseText',
  'symptoms',
  'labs',
  'medications',
  'comorbidities',
  'age',
  'sex',
  'message',
  'content',
  'freeText',
  'scenario',
  'input',
  'nested.email',
  // Generic fallbacks anywhere in structured logs
  '**.authorization',
  '**.apiKey',
  '**.accessToken',
  '**.refreshToken',
  '**.password',
  '**.token',
  '**.email',
  '**.notes',
  '**.note',
  '**.prompt',
  '**.query',
  '**.presentation',
  '**.caseText',
  '**.symptoms',
  '**.labs',
  '**.medications',
  '**.comorbidities',
  '**.age',
  '**.sex',
  '**.message',
  '**.content',
  '**.freeText',
  '**.scenario',
  '**.input',
];

module.exports = { REDACT_PATHS };

