/**
 * Trusted Clinical Guideline Source Registry
 * Each source has metadata for region, specialty, domain, and URL pattern.
 */

const TRUSTED_GUIDELINE_SOURCES = [
    {
        id: 'nice',
        name: 'NICE',
        fullName: 'National Institute for Health and Care Excellence',
        region: 'UK',
        specialty: 'Multidisciplinary',
        domain: 'https://www.nice.org.uk',
        urlPattern: 'https://www.nice.org.uk/guidance/{id}',
    },
    {
        id: 'who',
        name: 'WHO',
        fullName: 'World Health Organization',
        region: 'Global',
        specialty: 'Multidisciplinary',
        domain: 'https://www.who.int',
        urlPattern: 'https://www.who.int/publications/i/item/{id}',
    },
    {
        id: 'esc',
        name: 'ESC',
        fullName: 'European Society of Cardiology',
        region: 'Europe',
        specialty: 'Cardiology',
        domain: 'https://www.escardio.org',
        urlPattern: 'https://www.escardio.org/Guidelines/{id}',
    },
    {
        id: 'ers',
        name: 'ERS',
        fullName: 'European Respiratory Society',
        region: 'Europe',
        specialty: 'Respiratory Medicine',
        domain: 'https://www.ersnet.org',
        urlPattern: 'https://www.ersnet.org/guidelines/{id}',
    },
    {
        id: 'bts',
        name: 'BTS',
        fullName: 'British Thoracic Society',
        region: 'UK',
        specialty: 'Respiratory Medicine',
        domain: 'https://www.brit-thoracic.org.uk',
        urlPattern: 'https://www.brit-thoracic.org.uk/guidelines/{id}',
    },
    {
        id: 'esicm',
        name: 'ESICM',
        fullName: 'European Society of Intensive Care Medicine',
        region: 'Europe',
        specialty: 'Intensive Care',
        domain: 'https://www.esicm.org',
        urlPattern: 'https://www.esicm.org/guidelines/{id}',
    },
    {
        id: 'eular',
        name: 'EULAR',
        fullName: 'European Alliance of Associations for Rheumatology',
        region: 'Europe',
        specialty: 'Rheumatology',
        domain: 'https://www.eular.org',
        urlPattern: 'https://www.eular.org/guidelines/{id}',
    },
    {
        id: 'esmo',
        name: 'ESMO',
        fullName: 'European Society for Medical Oncology',
        region: 'Europe',
        specialty: 'Oncology',
        domain: 'https://www.esmo.org',
        urlPattern: 'https://www.esmo.org/guidelines/{id}',
    },
    {
        id: 'idsa',
        name: 'IDSA',
        fullName: 'Infectious Diseases Society of America',
        region: 'USA',
        specialty: 'Infectious Diseases',
        domain: 'https://www.idsociety.org',
        urlPattern: 'https://www.idsociety.org/practice-guideline/{id}',
    },
    {
        id: 'ada',
        name: 'ADA',
        fullName: 'American Diabetes Association',
        region: 'USA',
        specialty: 'Endocrinology / Diabetes',
        domain: 'https://diabetes.org',
        urlPattern: 'https://diabetes.org/standards-of-care/{id}',
    },
    {
        id: 'aha_acc',
        name: 'AHA/ACC',
        fullName: 'American Heart Association / American College of Cardiology',
        region: 'USA',
        specialty: 'Cardiology',
        domain: 'https://www.ahajournals.org',
        urlPattern: 'https://www.ahajournals.org/doi/{id}',
    },
    {
        id: 'gold',
        name: 'GOLD',
        fullName: 'Global Initiative for Chronic Obstructive Lung Disease',
        region: 'Global',
        specialty: 'Respiratory Medicine',
        domain: 'https://goldcopd.org',
        urlPattern: 'https://goldcopd.org/{id}',
    },
    {
        id: 'gina',
        name: 'GINA',
        fullName: 'Global Initiative for Asthma',
        region: 'Global',
        specialty: 'Respiratory Medicine',
        domain: 'https://ginasthma.org',
        urlPattern: 'https://ginasthma.org/gina-reports/{id}',
    },
];

module.exports = { TRUSTED_GUIDELINE_SOURCES };
