/**
 * Trusted Clinical Guideline Source Registry
 * Each source has metadata for region, specialty, domain, and URL pattern.
 */

const TRUSTED_GUIDELINE_SOURCES = [
    {
        id: 'nice',
        name: 'NICE',
        fullName: 'National Institute for Health and Care Excellence',
        region: 'UK',
        specialty: 'Multidisciplinary',
        domain: 'https://www.nice.org.uk',
        urlPattern: 'https://www.nice.org.uk/guidance/{id}',
    },
    {
        id: 'who',
        name: 'WHO',
        fullName: 'World Health Organization',
        region: 'Global',
        specialty: 'Multidisciplinary',
        domain: 'https://www.who.int',
        urlPattern: 'https://www.who.int/publications/i/item/{id}',
    },
    {
        id: 'esc',
        name: 'ESC',
        fullName: 'European Society of Cardiology',
        region: 'Europe',
        specialty: 'Cardiology',
        domain: 'https://www.escardio.org',
        urlPattern: 'https://www.escardio.org/Guidelines/{id}',
    },
    {
        id: 'ers',
        name: 'ERS',
        fullName: 'European Respiratory Society',
        region: 'Europe',
        specialty: 'Respiratory Medicine',
        domain: 'https://www.ersnet.org',
        urlPattern: 'https://www.ersnet.org/guidelines/{id}',
    },
    {
        id: 'bts',
        name: 'BTS',
        fullName: 'British Thoracic Society',
        region: 'UK',
        specialty: 'Respiratory Medicine',
        domain: 'https://www.brit-thoracic.org.uk',
        urlPattern: 'https://www.brit-thoracic.org.uk/guidelines/{id}',
    },
    {
        id: 'esicm',
        name: 'ESICM',
        fullName: 'European Society of Intensive Care Medicine',
        region: 'Europe',
        specialty: 'Intensive Care',
        domain: 'https://www.esicm.org',
        urlPattern: 'https://www.esicm.org/guidelines/{id}',
    },
    {
        id: 'eular',
        name: 'EULAR',
        fullName: 'European Alliance of Associations for Rheumatology',
        region: 'Europe',
        specialty: 'Rheumatology',
        domain: 'https://www.eular.org',
        urlPattern: 'https://www.eular.org/guidelines/{id}',
    },
    {
        id: 'esmo',
        name: 'ESMO',
        fullName: 'European Society for Medical Oncology',
        region: 'Europe',
        specialty: 'Oncology',
        domain: 'https://www.esmo.org',
        urlPattern: 'https://www.esmo.org/guidelines/{id}',
    },
    {
        id: 'idsa',
        name: 'IDSA',
        fullName: 'Infectious Diseases Society of America',
        region: 'USA',
        specialty: 'Infectious Diseases',
        domain: 'https://www.idsociety.org',
        urlPattern: 'https://www.idsociety.org/practice-guideline/{id}',
    },
    {
        id: 'ada',
        name: 'ADA',
        fullName: 'American Diabetes Association',
        region: 'USA',
        specialty: 'Endocrinology / Diabetes',
        domain: 'https://diabetes.org',
        urlPattern: 'https://diabetes.org/standards-of-care/{id}',
    },
    {
        id: 'aha_acc',
        name: 'AHA/ACC',
        fullName: 'American Heart Association / American College of Cardiology',
        region: 'USA',
        specialty: 'Cardiology',
        domain: 'https://www.ahajournals.org',
        urlPattern: 'https://www.ahajournals.org/doi/{id}',
        aliases: ['ACC/AHA', 'AHA/ASA', 'AHA/ACC/HFSA', 'ACC/AHA/SCAI', 'HFSA', 'SCAI', 'American Heart Association', 'American College of Cardiology'],
    },
    {
        id: 'gold',
        name: 'GOLD',
        fullName: 'Global Initiative for Chronic Obstructive Lung Disease',
        region: 'Global',
        specialty: 'Respiratory Medicine',
        domain: 'https://goldcopd.org',
        urlPattern: 'https://goldcopd.org/{id}',
    },
    {
        id: 'gina',
        name: 'GINA',
        fullName: 'Global Initiative for Asthma',
        region: 'Global',
        specialty: 'Respiratory Medicine',
        domain: 'https://ginasthma.org',
        urlPattern: 'https://ginasthma.org/gina-reports/{id}',
    },
    {
        id: 'easl',
        name: 'EASL',
        fullName: 'European Association for the Study of the Liver',
        region: 'Europe',
        specialty: 'Hepatology',
        domain: 'https://www.easl.eu',
        urlPattern: 'https://www.easl.eu/publications/{id}',
        aliases: ['European Association for the Study of the Liver'],
    },
    {
        id: 'kdigo',
        name: 'KDIGO',
        fullName: 'Kidney Disease: Improving Global Outcomes',
        region: 'Global',
        specialty: 'Nephrology',
        domain: 'https://kdigo.org',
        urlPattern: 'https://kdigo.org/guidelines/{id}',
        aliases: ['Kidney Disease Improving Global Outcomes'],
    },
    {
        id: 'asam',
        name: 'ASAM',
        fullName: 'American Society of Addiction Medicine',
        region: 'USA',
        specialty: 'Addiction Medicine',
        domain: 'https://www.asam.org',
        urlPattern: 'https://www.asam.org/quality-care/clinical-guidelines/{id}',
        aliases: ['American Society of Addiction Medicine'],
    },
    {
        id: 'apa',
        name: 'APA',
        fullName: 'American Psychiatric Association',
        region: 'USA',
        specialty: 'Psychiatry',
        domain: 'https://www.psychiatry.org',
        urlPattern: 'https://www.psychiatry.org/psychiatrists/practice/clinical-practice-guidelines/{id}',
        aliases: ['American Psychiatric Association'],
    },
    {
        id: 'acr',
        name: 'ACR',
        fullName: 'American College of Rheumatology',
        region: 'USA',
        specialty: 'Rheumatology',
        domain: 'https://rheumatology.org',
        urlPattern: 'https://rheumatology.org/clinical-practice-guidelines/{id}',
        aliases: ['American College of Rheumatology'],
    },
    {
        id: 'acg',
        name: 'ACG',
        fullName: 'American College of Gastroenterology',
        region: 'USA',
        specialty: 'Gastroenterology',
        domain: 'https://gi.org',
        urlPattern: 'https://gi.org/guidelines/{id}',
        aliases: ['American College of Gastroenterology', 'American Journal of Gastroenterology'],
    },
    {
        id: 'ssc',
        name: 'Surviving Sepsis Campaign',
        fullName: 'Surviving Sepsis Campaign',
        region: 'Global',
        specialty: 'Critical Care',
        domain: 'https://www.sccm.org',
        urlPattern: 'https://www.sccm.org/SurvivingSepsisCampaign/{id}',
        aliases: ['SSC', 'Surviving Sepsis'],
    },
    {
        id: 'cfpc',
        name: 'CFPC',
        fullName: 'College of Family Physicians of Canada',
        region: 'Canada',
        specialty: 'Family Medicine',
        domain: 'https://www.cfpc.ca',
        urlPattern: 'https://www.cfpc.ca/{id}',
        aliases: ['Canadian Family Physician', 'CFP'],
    },
    {
        id: 'alz',
        name: "Alzheimer's Association",
        fullName: "Alzheimer's Association",
        region: 'USA',
        specialty: 'Neurology',
        domain: 'https://www.alz.org',
        urlPattern: 'https://www.alz.org/{id}',
        aliases: ['JPAD', 'Lecanemab: Appropriate Use', 'Appropriate Use Recommendations'],
    },
    {
        id: 'erknet',
        name: 'ERKNet/IPNA',
        fullName: 'European Rare Kidney Disease Reference Network / International Pediatric Nephrology Association',
        region: 'Europe',
        specialty: 'Pediatric Nephrology',
        domain: 'https://www.erknet.org',
        urlPattern: 'https://www.erknet.org/{id}',
        aliases: ['IPNA', 'ERKNet'],
    },
    {
        id: 'ast',
        name: 'AST',
        fullName: 'American Society of Transplantation',
        region: 'USA',
        specialty: 'Transplantation',
        domain: 'https://www.myast.org',
        urlPattern: 'https://www.myast.org/{id}',
        aliases: ['AST IDCOP', 'American Society of Transplantation'],
    },
    {
        id: 'astct',
        name: 'ASTCT',
        fullName: 'American Society for Transplantation and Cellular Therapy',
        region: 'USA',
        specialty: 'Cellular Therapy',
        domain: 'https://www.astct.org',
        urlPattern: 'https://www.astct.org/{id}',
        aliases: ['American Society for Transplantation and Cellular Therapy'],
    },
    {
        id: 'nccn',
        name: 'NCCN',
        fullName: 'National Comprehensive Cancer Network',
        region: 'USA',
        specialty: 'Oncology',
        domain: 'https://www.nccn.org',
        urlPattern: 'https://www.nccn.org/guidelines/{id}',
        aliases: ['National Comprehensive Cancer Network'],
    },
    {
        id: 'ehra',
        name: 'EHRA',
        fullName: 'European Heart Rhythm Association',
        region: 'Europe',
        specialty: 'Cardiology / Electrophysiology',
        domain: 'https://www.escardio.org/Sub-specialty-communities/European-Heart-Rhythm-Association-(EHRA)',
        urlPattern: 'https://www.escardio.org/{id}',
        aliases: ['European Heart Rhythm Association'],
    },
    {
        id: 'eso',
        name: 'ESO',
        fullName: 'European Stroke Organisation',
        region: 'Europe',
        specialty: 'Stroke',
        domain: 'https://eso-stroke.org',
        urlPattern: 'https://eso-stroke.org/guidelines/{id}',
        aliases: ['European Stroke Organisation', 'European Stroke Organization'],
    },
    {
        id: 'asco',
        name: 'ASCO',
        fullName: 'American Society of Clinical Oncology',
        region: 'USA',
        specialty: 'Oncology',
        domain: 'https://www.asco.org',
        urlPattern: 'https://www.asco.org/guidelines/{id}',
        aliases: ['American Society of Clinical Oncology'],
    },
    {
        id: 'asge',
        name: 'ASGE',
        fullName: 'American Society for Gastrointestinal Endoscopy',
        region: 'USA',
        specialty: 'Gastroenterology',
        domain: 'https://www.asge.org',
        urlPattern: 'https://www.asge.org/guidelines/{id}',
        aliases: ['ASGE Standards of Practice Committee', 'American Society for Gastrointestinal Endoscopy'],
    },
    {
        id: 'eln',
        name: 'ELN',
        fullName: 'European LeukemiaNet',
        region: 'Europe',
        specialty: 'Haematology',
        domain: 'https://www.leukemia-net.org',
        urlPattern: 'https://www.leukemia-net.org/{id}',
        aliases: ['European LeukemiaNet'],
    },
    {
        id: 'ats',
        name: 'ATS',
        fullName: 'American Thoracic Society',
        region: 'USA',
        specialty: 'Respiratory Medicine',
        domain: 'https://www.thoracic.org',
        urlPattern: 'https://www.thoracic.org/statements/{id}',
        aliases: ['ATS/IDSA', 'American Thoracic Society'],
    },
    {
        id: 'aaaai',
        name: 'AAAAI/ACAAI',
        fullName: 'Joint Task Force on Practice Parameters',
        region: 'USA',
        specialty: 'Allergy / Immunology',
        domain: 'https://www.aaaai.org',
        urlPattern: 'https://www.aaaai.org/{id}',
        aliases: ['AAAAI', 'ACAAI', 'Joint Task Force on Practice Parameters'],
    },
    {
        id: 'esid',
        name: 'ESID',
        fullName: 'European Society for Immunodeficiencies',
        region: 'Europe',
        specialty: 'Immunology',
        domain: 'https://esid.org',
        urlPattern: 'https://esid.org/{id}',
        aliases: ['European Society for Immunodeficiencies'],
    },
    {
        id: 'sis',
        name: 'SIS',
        fullName: 'Surgical Infection Society',
        region: 'USA',
        specialty: 'Surgical Infection',
        domain: 'https://www.sisna.org',
        urlPattern: 'https://www.sisna.org/{id}',
        aliases: ['Surgical Infection Society', 'STOP-IT'],
    },
    {
        id: 'endocrine',
        name: 'Endocrine Society',
        fullName: 'Endocrine Society',
        region: 'USA',
        specialty: 'Endocrinology',
        domain: 'https://www.endocrine.org',
        urlPattern: 'https://www.endocrine.org/clinical-practice-guidelines/{id}',
        aliases: ["Cushing's disease guideline", 'Pituitary Society'],
    },
    {
        id: 'aao',
        name: 'AAO',
        fullName: 'American Academy of Ophthalmology',
        region: 'USA',
        specialty: 'Ophthalmology',
        domain: 'https://www.aao.org',
        urlPattern: 'https://www.aao.org/preferred-practice-pattern/{id}',
        aliases: ['American Academy of Ophthalmology', 'Preferred Practice Pattern'],
    },
    {
        id: 'aad',
        name: 'AAD',
        fullName: 'American Academy of Dermatology',
        region: 'USA',
        specialty: 'Dermatology',
        domain: 'https://www.aad.org',
        urlPattern: 'https://www.aad.org/{id}',
        aliases: ['EuroGuiDerm', 'EADV', 'American Academy of Dermatology'],
    },
    {
        id: 'ata',
        name: 'ATA',
        fullName: 'American Thyroid Association',
        region: 'USA',
        specialty: 'Endocrinology',
        domain: 'https://www.thyroid.org',
        urlPattern: 'https://www.thyroid.org/{id}',
        aliases: ['American Thyroid Association'],
    },
    {
        id: 'wfh',
        name: 'WFH',
        fullName: 'World Federation of Hemophilia',
        region: 'Global',
        specialty: 'Haematology',
        domain: 'https://wfh.org',
        urlPattern: 'https://wfh.org/{id}',
        aliases: ['World Federation of Hemophilia', 'World Federation of Haemophilia'],
    },
    {
        id: 'shea',
        name: 'SHEA',
        fullName: 'Society for Healthcare Epidemiology of America',
        region: 'USA',
        specialty: 'Infection Prevention',
        domain: 'https://shea-online.org',
        urlPattern: 'https://shea-online.org/{id}',
        aliases: ['SHEA/IDSA', 'SHEA/IDSA/APIC', 'APIC'],
    },
    {
        id: 'tts',
        name: 'TTS',
        fullName: 'The Transplantation Society',
        region: 'Global',
        specialty: 'Transplantation',
        domain: 'https://tts.org',
        urlPattern: 'https://tts.org/{id}',
        aliases: [
            'The Transplantation Society',
            'International Consensus Guidelines on the Management of Cytomegalovirus',
            'CMV in Solid-organ Transplantation',
        ],
    },
];

module.exports = { TRUSTED_GUIDELINE_SOURCES };
