'use strict';

const AI_DISCLAIMER = 'This output was generated by artificial intelligence for research support only. It must not be used as a substitute for clinical judgement. Always verify findings against the primary source before informing any patient care or policy decision.';

module.exports = {
    AI_DISCLAIMER,
};
