/**
 * LLM text generation and prompt builders (Mistral, Gemini).
 * Embeddings for RAG live in server/embeddings.js.
 */
const logger = require('../config/logger');

const AI_PROVIDERS = {
    mistral: {
        name: 'Mistral AI',
        url: 'https://api.mistral.ai/v1/chat/completions',
        models: {
            'mistral-small': 'mistral-small-2603',
        },
    },
};

// Pinned model versions for reproducibility and deterministic outputs.
const PINNED_MODELS = {
    gemini: 'gemini-2.5-flash-lite',
    geminiQuality: 'gemini-2.5-flash',
    mistral: 'mistral-small-2603',
};

// Temperature presets for medical use-cases.
const TEMPERATURE = {
    analysis: 0.7,      // Creative but grounded
    synthesis: 0.2,     // Highly deterministic for evidence synthesis
    synopsis: 0.15,     // Maximum grounding — pure factual extraction from abstract
    quiz: 0.5,          // Balanced variety
    explain: 0.6,       // Patient-friendly but consistent
};

const MAX_OUTPUT_TOKENS = {
    synthesis: 2800,
};

const AI_DISCLAIMER = 'This output was generated by artificial intelligence for research support only. It must not be used as a substitute for clinical judgement. Always verify findings against the primary source before informing any patient care or policy decision.';

/**
 * @param {object} options
 * @param {import('../../config').serverConfig} options.serverConfig
 * @param {typeof fetch} [options.fetchImpl]
 */
const { CircuitBreaker } = require('./circuitBreaker');
const { buildProxyService } = require('./externalApiProxy');

function createAiService({ serverConfig, fetchImpl = fetch, onLlmCall = null }) {
    const f = fetchImpl;
    const proxy = buildProxyService({ serverConfig, fetchImpl: f });

    async function emitLlmCall(meta) {
        if (typeof onLlmCall !== 'function') return;
        try {
            await onLlmCall(meta);
        } catch (err) {
            logger.warn({ err }, 'LLM usage log callback failed');
        }
    }

    async function withUsageLog({ operation, provider, model, prompt, topic, userId }, fn) {
        const started = Date.now();
        try {
            const text = await fn();
            await emitLlmCall({
                operation,
                provider,
                model,
                topic,
                userId,
                prompt,
                response: text,
                success: true,
                durationMs: Date.now() - started,
            });
            return text;
        } catch (err) {
            await emitLlmCall({
                operation,
                provider,
                model,
                topic,
                userId,
                prompt,
                response: '',
                success: false,
                errorMessage: err.message,
                durationMs: Date.now() - started,
            });
            throw err;
        }
    }

    // Circuit breakers protect against cascading failures when LLM APIs degrade
    const mistralBreaker = new CircuitBreaker(callMistralAIRaw, { failureThreshold: 5, resetTimeoutMs: 30000 });
    const geminiBreaker = new CircuitBreaker(callGeminiRaw, { failureThreshold: 5, resetTimeoutMs: 30000 });
    // Note: streaming functions are not circuit-broken at the generator level
    // because the initial HTTP request is the critical failure point and stream
    // errors are handled per-chunk. The fetch timeouts in safeFetch already protect
    // against hanging connections.

    async function callMistralAIRaw(prompt, model = PINNED_MODELS.mistral, { temperature = TEMPERATURE.analysis, maxOutputTokens } = {}) {
        return proxy.mistralChat(prompt, { model, temperature, maxOutputTokens });
    }

    // Kept for backward compatibility with provider selection surfaces.
    async function callHuggingFace(prompt, model = 'mistralai/Mistral-7B-Instruct-v0.2') {
        if (!serverConfig.keys.huggingface) {
            throw new Error('HuggingFace API key not configured');
        }
        const response = await f(`https://api-inference.huggingface.co/models/${model}`, {
            method: 'POST',
            headers: {
                Authorization: `Bearer ${serverConfig.keys.huggingface}`,
                'Content-Type': 'application/json',
            },
            body: JSON.stringify({
                inputs: prompt,
                parameters: {
                    max_new_tokens: 512,
                    temperature: 0.7,
                    return_full_text: false,
                },
            }),
        });
        if (!response.ok) {
            const errText = await response.text();
            throw new Error(`HF API error: ${response.status} - ${errText}`);
        }
        const data = await response.json();
        if (Array.isArray(data) && data[0]?.generated_text) return data[0].generated_text;
        if (data?.generated_text) return data.generated_text;
        return typeof data === 'string' ? data : 'No response';
    }

    async function callGeminiRaw(prompt, model = PINNED_MODELS.gemini, { temperature = TEMPERATURE.analysis, maxOutputTokens, timeoutMs = 45000 } = {}) {
        logger.debug({ model, temperature }, 'Calling Gemini');
        return proxy.geminiGenerate(prompt, { model, temperature, maxOutputTokens, timeoutMs });
    }

    /**
     * Stream Gemini response as an async generator of text chunks.
     */
    async function* callGeminiStreamRaw(prompt, model = PINNED_MODELS.gemini, { temperature = TEMPERATURE.analysis, maxOutputTokens } = {}) {
        const apiKey = serverConfig.keys.gemini;
        if (!apiKey) throw new Error('Gemini API key not configured');

        const modelName = model.includes('gemini') ? model : PINNED_MODELS.gemini;
        const url = `https://generativelanguage.googleapis.com/v1beta/models/${modelName}:streamGenerateContent?alt=sse`;

        logger.debug({ model: modelName, temperature }, 'Calling Gemini stream');

        const response = await f(url, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'x-goog-api-key': apiKey,
            },
            body: JSON.stringify({
                contents: [{ role: 'user', parts: [{ text: prompt }] }],
                generationConfig: {
                    temperature,
                    maxOutputTokens: maxOutputTokens ?? (prompt.length > 5000 ? 2500 : 1024),
                    topP: 0.95,
                    topK: 40,
                },
            }),
        });

        if (!response.ok) {
            const errText = await response.text();
            throw new Error(`Gemini stream error: ${response.status} ${errText.slice(0, 200)}`);
        }

        const stream = response.body;
        const decoder = new TextDecoder();
        let buffer = '';

        try {
            for await (const chunk of stream) {
                buffer += decoder.decode(chunk, { stream: true });
                const lines = buffer.split('\n');
                buffer = lines.pop() || '';
                for (const line of lines) {
                    const trimmed = line.trim();
                    if (!trimmed.startsWith('data: ')) continue;
                    const payload = trimmed.slice(6);
                    if (payload === '[DONE]') return;
                    try {
                        const data = JSON.parse(payload);
                        const textChunk = data.candidates?.[0]?.content?.parts?.[0]?.text;
                        if (textChunk) yield textChunk;
                        if (data.promptFeedback?.blockReason) {
                            throw new Error(`Content blocked: ${data.promptFeedback.blockReason}`);
                        }
                    } catch (e) {
                        if (e.message?.includes('blocked')) throw e;
                        // Ignore parse errors for malformed SSE lines
                    }
                }
            }
        } finally {
            if (stream && typeof stream.destroy === 'function') stream.destroy();
        }
    }

    /**
     * Stream Mistral response as an async generator of text chunks.
     */
    async function* callMistralStreamRaw(prompt, model = PINNED_MODELS.mistral, { temperature = TEMPERATURE.analysis, maxOutputTokens } = {}) {
        const response = await f('https://api.mistral.ai/v1/chat/completions', {
            method: 'POST',
            headers: {
                Authorization: `Bearer ${serverConfig.keys.mistral}`,
                'Content-Type': 'application/json',
            },
            body: JSON.stringify({
                model,
                messages: [
                    { role: 'system', content: 'You are a medical research assistant. Provide accurate, evidence-based analysis.' },
                    { role: 'user', content: prompt },
                ],
                max_tokens: maxOutputTokens ?? (prompt.length > 5000 ? 1500 : 512),
                temperature,
                stream: true,
            }),
        });

        if (!response.ok) {
            const errText = await response.text();
            throw new Error(`Mistral stream error: ${response.status} - ${errText}`);
        }

        const stream = response.body;
        const decoder = new TextDecoder();
        let buffer = '';

        try {
            for await (const chunk of stream) {
                buffer += decoder.decode(chunk, { stream: true });
                const lines = buffer.split('\n');
                buffer = lines.pop() || '';
                for (const line of lines) {
                    const trimmed = line.trim();
                    if (!trimmed.startsWith('data: ')) continue;
                    const payload = trimmed.slice(6);
                    if (payload === '[DONE]') return;
                    try {
                        const data = JSON.parse(payload);
                        const textChunk = data.choices?.[0]?.delta?.content;
                        if (textChunk) yield textChunk;
                    } catch (err) {
                        logger.debug({ err }, 'Ignoring malformed SSE line from AI provider');
                    }
                }
            }
        } finally {
            if (stream && typeof stream.destroy === 'function') stream.destroy();
        }
    }

    // Public API: circuit-breaker-wrapped versions for non-streaming calls
    async function callClaudeRaw(prompt, model = 'claude-haiku-4-5-20251001', { temperature = TEMPERATURE.analysis, maxOutputTokens = 2048, timeoutMs = 45000 } = {}) {
        return proxy.claudeMessages(prompt, { model, temperature, maxOutputTokens, timeoutMs });
    }

    async function callMistralAI(prompt, model, options = {}) {
        const { usage, ...rest } = options;
        if (!usage?.operation) return mistralBreaker.fire(prompt, model, rest);
        return withUsageLog(
            { operation: usage.operation, provider: 'mistral', model, prompt, topic: usage.topic, userId: usage.userId },
            () => mistralBreaker.fire(prompt, model, rest)
        );
    }
    async function callGemini(prompt, model, options = {}) {
        const { usage, ...rest } = options;
        if (!usage?.operation) return geminiBreaker.fire(prompt, model, rest);
        return withUsageLog(
            { operation: usage.operation, provider: 'gemini', model, prompt, topic: usage.topic, userId: usage.userId },
            () => geminiBreaker.fire(prompt, model, rest)
        );
    }

    return {
        callMistralAI,
        callHuggingFace,
        callGemini,
        callClaude: callClaudeRaw,
        callGeminiStream: callGeminiStreamRaw,
        callMistralStream: callMistralStreamRaw,
        AI_PROVIDERS,
        // Expose breaker health for monitoring endpoints
        _breakers: { mistral: mistralBreaker, gemini: geminiBreaker },
    };
}


const prompts = require('../prompts');

module.exports = {
    createAiService,
    ...prompts,
    AI_PROVIDERS,
    PINNED_MODELS,
    TEMPERATURE,
    MAX_OUTPUT_TOKENS,
    AI_DISCLAIMER,
};
