'use strict';

/**
 * Persists articles and guidelines accessed during live searches as permanent system resources.
 *
 * Two-layer store:
 *   1. article_cache  — raw article metadata for fast future retrieval, retraction checks,
 *                       and avoiding repeat API calls to PubMed/SS/OpenAlex.
 *   2. teaching_objects (paper) — topic-linked articles for the knowledge graph so the
 *                                 learning agent can surface them as resources for MCQs,
 *                                 synopses, and guideline alignment.
 *
 * Runs fire-and-forget after search results are sent — zero latency impact.
 */

const logger = require('../config/logger');

/** Maximum articles to persist per search (top-ranked only). */
const MAX_PERSIST = 10;

/**
 * Normalise a topic string to a stable lowercase slug.
 * Mirrors the pattern used elsewhere in the codebase.
 */
function normalizeTopic(topic) {
    return String(topic || '')
        .toLowerCase()
        .replace(/[^a-z0-9\s-]/g, '')
        .replace(/\s+/g, ' ')
        .trim();
}

/**
 * Extract citation count from whichever field the source uses.
 */
function citationCount(article) {
    return Number(article.citationCount ?? article.citations ?? article.n_citations ?? 0) || 0;
}

/**
 * Build a stable object_key for a paper linked to a specific search topic.
 * Format: paper:<normalized-topic>:<article-uid>
 */
function paperObjectKey(normalizedTopic, articleUid) {
    return `paper:${normalizedTopic}:${articleUid}`.slice(0, 240);
}

/**
 * Store one article in article_cache (permanent — no expiry set).
 * Uses ON CONFLICT to update only the citation count if the article was seen before,
 * keeping original fetch timestamp intact.
 */
async function cacheArticle(db, article) {
    const uid = article.uid;
    if (!uid) return;

    try {
        await db.run(
            `INSERT INTO article_cache (id, source, data, title, authors, abstract, publication_date, journal, citation_count, fetched_at, expires_at)
             VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP, NULL)
             ON CONFLICT(id) DO UPDATE SET
                 citation_count = excluded.citation_count,
                 data = excluded.data`,
            [
                uid,
                article._source || 'unknown',
                JSON.stringify(article),
                String(article.title || '').slice(0, 500),
                JSON.stringify(Array.isArray(article.authors) ? article.authors.slice(0, 20) : []),
                String(article.abstract || '').slice(0, 4000),
                String(article.pubdate || article.year || ''),
                String(article.source || article.journal || '').slice(0, 200),
                citationCount(article),
            ]
        );
    } catch (err) {
        // Non-critical — log and continue
        logger.debug({ err, uid }, 'articlePersistence: article_cache upsert failed');
    }
}

/**
 * Store one article in teaching_objects linked to the search topic.
 * Uses DO NOTHING on conflict — existing high-confidence paper objects
 * generated by seeding scripts take precedence.
 */
async function persistPaperObject(db, article, normalizedTopic, rawTopic) {
    const uid = article.uid;
    if (!uid || !normalizedTopic) return;

    const objectKey = paperObjectKey(normalizedTopic, uid);

    try {
        await db.run(
            `INSERT INTO teaching_objects (
                object_key, object_type, article_uid, normalized_topic, topic, title,
                object_payload, provider, model, confidence, generated_at, created_at, updated_at
             ) VALUES (?, 'paper', ?, ?, ?, ?, ?, ?, NULL, 0.6, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
             ON CONFLICT(object_key) DO NOTHING`,
            [
                objectKey,
                uid,
                normalizedTopic,
                rawTopic || normalizedTopic,
                String(article.title || '').slice(0, 500),
                JSON.stringify({
                    uid,
                    title: article.title,
                    abstract: article.abstract,
                    authors: article.authors,
                    journal: article.source || article.journal,
                    year: article.pubdate?.split(' ')[0] || article.year,
                    citationCount: citationCount(article),
                    source: article._source,
                    pmid: article.pmid || null,
                    pmcid: article.pmcid || null,
                    doi: article.doi || null,
                    openAccess: article.openAccess || article.isFree || !!article.pmcid || false,
                    pubtype: article.pubtype || article._pubtype || null,
                    _quality: article._quality || null,
                    _ebmScore: article._ebmScore || null,
                }),
                article._source || 'unknown',
            ]
        );
    } catch (err) {
        logger.debug({ err, uid, objectKey }, 'articlePersistence: teaching_object upsert failed');
    }
}

/**
 * Main entry point — call this fire-and-forget after sending search results.
 *
 * @param {object}   db       - Database adapter (must expose db.run)
 * @param {object[]} articles - Ranked, sanitized article list from the search pipeline
 * @param {string}   query    - The raw search query (used as topic label)
 */
async function persistSearchedArticles(db, articles, query) {
    if (!db?.run || !Array.isArray(articles) || articles.length === 0 || !query) return;

    const rawTopic = String(query).trim().slice(0, 240);
    const normalizedTopic = normalizeTopic(rawTopic);
    if (!normalizedTopic) return;

    const toStore = articles
        .filter((a) => a?.uid)
        .slice(0, MAX_PERSIST);

    // Run concurrently — all are independent upserts
    await Promise.allSettled(
        toStore.flatMap((article) => [
            cacheArticle(db, article),
            persistPaperObject(db, article, normalizedTopic, rawTopic),
        ])
    );

    logger.debug(
        { topic: normalizedTopic, count: toStore.length },
        'articlePersistence: persisted search-accessed articles'
    );
}

module.exports = { persistSearchedArticles };
